In [5]:
#import the library
import numpy as np



In [7]:
lst=[1,2,3,4]
np.array(lst)

array([1, 2, 3, 4])

In [13]:
lst=[1,2,3,4,8]
arr=np.array(lst)
type(arr)

numpy.ndarray

In [7]:
lst1 =[1,2,3]
lst2 =[2,3,4]
lst3 =[9,7,5]

arr1=np.array([lst1,lst2,lst3])

In [17]:
arr.shape

(5,)

In [21]:
arr1

array([[1, 2, 3],
       [2, 3, 4],
       [9, 7, 5]])

In [9]:
arr1.shape

(3, 3)

In [15]:
arr

array([1, 2, 3, 4, 8])

In [17]:
#indexing
arr[3]

4

In [25]:
arr[-1]

8

In [27]:
arr[:-1]

array([1, 2, 3, 5])

In [31]:
arr1[::-1]

array([[9, 7, 5],
       [2, 3, 4],
       [1, 2, 3]])

In [35]:
arr1[::-3]

array([[9, 7, 5]])

In [37]:
arr1[-3::]

array([[1, 2, 3],
       [2, 3, 4],
       [9, 7, 5]])

In [39]:
arr1[1:,1:3]

array([[3, 4],
       [7, 5]])

In [41]:
arr1[1:,3:]

array([], shape=(2, 0), dtype=int32)

In [9]:
import numpy as np

arr2= np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g'])

print(arr2[1:5])

['b' 'c' 'd' 'e']


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [13]:
arr = np.array([1,2,3,4,5])
x= arr.copy()
arr[0]= 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)

print("shape of array",arr.shape)

[[[[[1 2 3 4]]]]]
shape of array (1, 1, 1, 1, 4)


In [1]:
import numpy as np
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [3]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [5]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [7]:
import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [9]:
#for desending
import numpy as np
arr = np.array([3, 2, 0, 1])
sorted_arr = np.sort(arr)[::-1]
print(sorted_arr)

[3 2 1 0]


In [18]:
from numpy import random
x= random.randint(100)
print(x)

21


In [22]:
from numpy import random
x= random.randint(100, size=(5))
print(x)

[24 49  6 45 86]


In [28]:
from numpy import random
x= random.randint(100, size=(3,5))
print(x,type(x))

[[99 98 65 18 41]
 [33 18 97 72 20]
 [30 77 79  8 28]] <class 'numpy.ndarray'>


In [32]:
import numpy as np

np.arange(1,20,2,
           dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [36]:
import numpy as np

np.linspace(3.5,10,3,
             dtype=np.int32)

array([ 3,  6, 10])

In [38]:
import numpy as np

np.empty([4,3],
         dtype = np.int32,
         order = "f")

array([[4128860, 6619251, 3539056],
       [6029375, 7536754, 4259932],
       [3801155, 7471196, 7340144],
       [5570652, 6946913, 6357060]])