In [1]:
###**`Numpy Basics`**

In [1]:
import numpy as np

In [2]:
#1-d Array
arr1=np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
print(arr1.ndim)

1


In [6]:
#2-d Array
arr2=np.array([[1,2,3],[4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(arr2.ndim)

2


In [9]:
arr3=np.zeros((2,3))

In [10]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
print(arr3.ndim)

2


In [12]:
type(arr3)

numpy.ndarray

In [13]:
arr4=np.ones((3,3))

In [14]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [16]:
# Accessing Array Elements
arr1=np.array([1,2,3,4,5])

print(arr1[0])

1


In [17]:
arr1[3]

4

In [18]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#2nd element on 1st row
arr2[0,1]

2

In [20]:
arr2[1]

array([4, 5, 6])

In [21]:
arr2[1,1]

5

In [22]:
import numpy as np

arr3 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr3[1:5])

[2 3 4 5]


In [23]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[4:])

[5 6 7]


In [24]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr5[:4])

[1 2 3 4]


In [25]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr6[-3:-1])

[5 6]


In [26]:
#Return every other element from index 1 to index 5:

arr7 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr7[1:5:2])

[2 4]


In [27]:
# Shape of an Array: shape that returns a tuple with each index having the number of corresponding elements.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [28]:
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [30]:
# Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [31]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [32]:
# NumPy Joining Array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [33]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [35]:
#Splitting NumPy Arrays
# Splitting is reverse operation of Joining.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [37]:
# Random Numbers
# NumPy offers the random module to work with random numbers.
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(100)

print(x)

69


In [38]:
# Random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand()

print(x)

0.35775707640833765


In [39]:
# Generate Random Array
from numpy import random

x=random.randint(100, size=(5))

print(x)

[33 70 37 90 46]


In [40]:
# A 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[54 70 65 35 33]
 [ 5  3 87 31 26]
 [51 52 99 68  6]]


In [41]:
# Generate a 1-D array containing 5 random floats:
from numpy import random

x = random.rand(5)

print(x)

[0.00126727 0.85019119 0.88097629 0.41560203 0.21878605]


In [42]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.36517783 0.1007558  0.05415234 0.68518183 0.33403738]
 [0.20760132 0.64005242 0.87520659 0.23058077 0.04632103]
 [0.56609682 0.4034898  0.53121428 0.9987199  0.4830558 ]]
